spring:
  application:
    name: orchestrator

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true

logging:
  file:
    name: logs/application.log
    path: /logs

resilience4j:
  retry:
    instances:
      productFetcherRetry:
        maxAttempts: 3
        waitDuration: 2s
        retry-exceptions:
          - java.lang.RuntimeException